# Generated by Django 3.2.8 on 2021-10-21 15:37

import core.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ml.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('django_celery_results', '0010_remove_duplicate_indices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorage, upload_to=ml.models.user_directory_path)),
                ('algorithm', models.PositiveSmallIntegerField(choices=[(0, 'K-means'), (1, 'Spectral Clustering'), (2, 'Hidden Markov model'), (3, 'Gaussian Mixture'), (4, 'Neural networks')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.dataset')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_results.taskresult')),
            ],
        ),
        migrations.CreateModel(
            name='KmeansParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.PositiveSmallIntegerField(default=8)),
                ('init', models.PositiveSmallIntegerField(choices=[(0, 'k-means++'), (1, 'random')], default=0)),
                ('n_init', models.PositiveSmallIntegerField(default=10)),
                ('max_iter', models.PositiveSmallIntegerField(default=300)),
                ('algorithm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ml.algorithmdata')),
            ],
        ),
    ]
