# Generated by Django 3.2.8 on 2021-10-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_dataset_owner'),
        ('django_celery_results', '0010_remove_duplicate_indices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.PositiveSmallIntegerField(choices=[(0, 'K-means'), (1, 'Singular-value Decomposition'), (2, 'Hidden Markov model'), (3, 'Gaussian Mixture'), (4, 'Neural networks')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.dataset')),
                ('task_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_results.taskresult')),
            ],
        ),
    ]
