# Generated by Django 3.2.8 on 2021-10-19 19:49

import core.storage_backends
from django.db import migrations, models
import ml.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='task_result',
            new_name='task',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='result_data',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorage, upload_to=ml.models.user_directory_path),
        ),
    ]
