# Generated by Django 3.2.8 on 2021-10-22 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_auto_20211022_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmdata',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='algorithmdata',
            name='dataset',
        ),
        migrations.AddField(
            model_name='algorithmdata',
            name='clusters_count',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algorithmdata',
            name='algorithm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'K-means'), (1, 'Spectral Clustering'), (2, 'Gaussian Mixture')]),
        ),
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithms', models.ManyToManyField(to='ml.AlgorithmData')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.dataset')),
            ],
        ),
    ]
