# Generated by Django 3.2.8 on 2021-10-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20211022_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustering',
            name='algorithms',
        ),
        migrations.AddField(
            model_name='algorithmdata',
            name='clustering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ml.clustering'),
            preserve_default=False,
        ),
    ]
