# Generated by Django 3.2.8 on 2021-10-23 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0003_auto_20211023_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustering',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KmeansParameters',
        ),
    ]
