# Generated by Django 3.2.8 on 2021-10-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20211023_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmdata',
            name='task',
        ),
        migrations.AddField(
            model_name='algorithmdata',
            name='task_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
