# Generated by Django 3.2.8 on 2021-10-25 17:57

import core.storage_backends
from django.db import migrations, models
import ml.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_auto_20211025_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmdata',
            name='clusters_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='algorithmdata',
            name='result_data',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorageOverwrite, upload_to=ml.models.user_directory_path),
        ),
    ]
