# Generated by Django 3.2.8 on 2021-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustering',
            name='creator',
        ),
        migrations.AddField(
            model_name='clustering',
            name='name',
            field=models.CharField(default='ja', max_length=50),
            preserve_default=False,
        ),
    ]
