# Generated by Django 3.2.8 on 2021-12-04 13:13

import core.storage_backends
from django.db import migrations, models
import ml.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_auto_20211121_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmdata',
            name='plot_2d_points',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorageOverwrite, upload_to=ml.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='algorithmdata',
            name='plot_3d_points',
            field=models.FileField(blank=True, null=True, storage=core.storage_backends.PrivateMediaStorageOverwrite, upload_to=ml.models.user_directory_path),
        ),
    ]
